image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Python Environment
    init: >
      echo "Creating Python environment..."
      python3 -m venv venv
      echo "source venv/bin/activate" >> .bashrc
    command: >
      source venv/bin/activate
      pip install prefect beautifulsoup4 requests psycopg2-binary jupyter

  - name: Launch Prefect Server
    command: prefect orion start

  - name: Launch Jupyter (Optional)
    command: jupyter notebook --ip=0.0.0.0 --port=8081

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

# Additional Gitpod configuration can go here (e.g., environment variables, prebuilds)
